h_timeVAE:
  latent_dim: 8
  hidden_layer_sizes:
    - 15
    - 30
    - 60
    - 90
    - 120
    - 150
    - 180
    - 210
    - 240
  reconstruction_wt: 3.0
  batch_size: 16
  use_residual_conn: true
  trend_poly: 3
  custom_seas:
    - [24, 1]
  layers_per_conv_block: 2
  hierarchical_levels: 4

timeVAE:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
  use_residual_conn: true
  trend_poly: 0
  custom_seas: null

vae_dense:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16

vae_conv:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
