h_timeVAE:
  latent_dim: 8
  hidden_layer_sizes:
    - 15
    - 30
    - 60
    - 90
    - 120
  reconstruction_wt: 3.0
  batch_size: 16
  use_residual_conn: true
  trend_poly: 6
  custom_seas:
    - [24, 1]
    - [7, 24]
  layers_per_conv_block: 1
  hierarchical_levels: 4
  latent_indexes:
    - 3
    - 2
    - 1
    - 0

timeVAE:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
  use_residual_conn: true
  trend_poly: 6
  custom_seas:
    - [24, 1]
    - [7, 24]

vae_dense:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16

vae_conv:
  latent_dim: 8
  hidden_layer_sizes:
    - 50
    - 100
    - 200
  reconstruction_wt: 3.0
  batch_size: 16
